# Create a new publication
POST http://localhost:3000/api/publications/create?type=video HTTP/1.1
Content-Type: application/json

{
  "state": "publication",
  "userId": "userid",
  "title": "publication title",
  "videoLink": "https://youtu.be/kqYiiZhPuLk?si=vznGw96-FQUFCgpU"
}

###

# Get all publications
GET http://localhost:3000/api/publications HTTP/1.1

###

# Get publication
GET http://localhost:3000/api/publications/bba31fdd3-2d5f-4e22-9bd1-ef46b78aedfd HTTP/1.1

###

# Delete publication
DELETE http://localhost:3000/api/publications/ba31fdd3-2d5f-4e22-9bd1-ef46b78aedfd HTTP/1.1

###

# Update publications
PUT http://localhost:3000/api/publications/ba31fdd3-2d5f-4e22-9bd1-ef46b78aedfd HTTP/1.1
Content-Type: application/json

{
    "userId": "userId",
    "id": "ba31fdd3-2d5f-4e22-9bd1-ef46b78aedfd",
    "status": "draft",
    "comments": [{value: "comment"}],
    "type": "video"
}
