# Create a new publication
POST http://localhost:3030/api/publications/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NWJmNDEwYjNlMjlkZGU3NDdhMWZjM2MiLCJlbWFpbCI6InpAei5jb20iLCJmaXJzdG5hbWUiOiJOYW1lIiwibGFzdG5hbWUiOiJjYWwnIiwiaWF0IjoxNzA3MDM1NjEyLCJleHAiOjE3MDc4OTk2MTJ9.rPR1OmcsMO9ACe8PW87xErm20BjuPKg0AFVnR7PmNn4

{
  "authorId": "65be1a501725214123c69d32",
  "title": "first video of second user",
  "videoLink": "https://youtu.be/kqYiiZhPuLk?si=vznGw96-FQUFCgpU",
  "type": "video",
  "tags": ["99584b65-6656-4347-bb88-a180bfdba6f8"]
}

###

# Get all publications
GET http://localhost:3030/api/publications HTTP/1.1

###

###

# Get all publications of specific user
GET http://localhost:3030/api/publications?authorId=65be1a501725214123c69d32 HTTP/1.1

###

# Get publication
GET http://localhost:3030/api/publications/38338f12-957f-4d13-9810-05bbbf688ab1 HTTP/1.1

###

###

# Search publication
GET http://localhost:3030/api/publications/search?title=first HTTP/1.1

###

# Delete publication
DELETE http://localhost:3030/api/publications/38338f12-957f-4d13-9810-05bbbf688ab1 HTTP/1.1
Content-Type: application/json

{
  "userId": "65bd8fc91725214123c69d2c"
}

###

# Update publications
PATCH http://localhost:3030/api/publications/38338f12-957f-4d13-9810-05bbbf688ab1 HTTP/1.1
Content-Type: application/json

{
    "authorId": "65bd8fc91725214123c69d2c",
    "title": "new title 2",
    "type": "video",
    "tags": ["f0964118-2a3d-479d-a92b-c70218365b73"]
}
