# Get all comments for a publication
GET http://localhost:3030/api/publications/eba8c5be-c4be-41c0-9e31-6bf0ba155c09/comments?page=1 HTTP/1.1

###

# Create a new comment
POST http://localhost:3030/api/publications/eba8c5be-c4be-41c0-9e31-6bf0ba155c09/comments HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NWJkOGZjOTE3MjUyMTQxMjNjNjlkMmMiLCJlbWFpbCI6ImFAYi5jb20iLCJmaXJzdG5hbWUiOiJmaXJzdCIsImxhc3RuYW1lIjoibGFzdCIsImlhdCI6MTcwNjk4OTgyMiwiZXhwIjoxNzA3ODUzODIyfQ.19_bzC8zQ1EHhB0gY3uEMKNvz3htLRf96Df0IYZRU0I

{
  "value": "Comment number 3",
  "userId": "65bd8fc91725214123c69d2c"
}

###

# Delete comment
DELETE http://localhost:3030/api/publications/eba8c5be-c4be-41c0-9e31-6bf0ba155c09/comments/9794462a-ca0e-49eb-941b-10e311a1b529 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NWJkOGZjOTE3MjUyMTQxMjNjNjlkMmMiLCJlbWFpbCI6ImFAYi5jb20iLCJmaXJzdG5hbWUiOiJmaXJzdCIsImxhc3RuYW1lIjoibGFzdCIsImlhdCI6MTcwNjk4OTgyMiwiZXhwIjoxNzA3ODUzODIyfQ.19_bzC8zQ1EHhB0gY3uEMKNvz3htLRf96Df0IYZRU0I

###
