# Get all comments for post
GET http://localhost:3030/api/posts/ae73a1ab-34fc-4290-a9e4-676beead191f/comments?page=1 HTTP/1.1

###

# Create a new comment for post
POST http://localhost:3030/api/posts/7e887c7f-1d9f-459a-ba81-c3e111d24bf5/comments HTTP/1.1
Content-Type: application/json

{
  "message": "Comment",
  "userId": "658170cbb954e9f5b905ccf4"
}

###

# Delete comment
DELETE http://localhost:3030/api/posts/c4313d9c-af77-4b6a-99a5-b7a969327021/comments/commentid HTTP/1.1
Content-Type: application/json

{
  "userId": "658170cbb954e9f5b905ccf4"
}

###
